%% RotVecHinge
% The following script takes a vector that represents the axis of rotation,
% and generates the rotation matrix required to rotate any vector about
% that axis an angle of alpha
%
% Dario Calderon 2016
%
function Rot_mat = RotVecHinge(X,Y,Z,alpha)

Rot_mat = [cos(alpha)+(X^2)*(1-cos(alpha)), ...
    X*Y*(1-cos(alpha))-Z*sin(alpha), ...
    X*Z*(1-cos(alpha))+Y*(sin(alpha));...
    Y*X*(1-cos(alpha))+Z*sin(alpha), ...
    cos(alpha)+(Y^2)*(1-cos(alpha)), ...
    Y*Z*(1-cos(alpha))-X*(sin(alpha));...
    Z*X*(1-cos(alpha))-Y*(sin(alpha)), ...
    Z*Y*(1-cos(alpha))+X*sin(alpha), ...
    cos(alpha)+(Z^2)*(1-cos(alpha))];
end